stages:
  - build
  - deploy

variables:
  IMAGE_TAG: latest
  ECR_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  IMAGE_NAME: flask-app

build:
  stage: build

  image: docker:24

  services:
    - name: docker:24-dind
      command: ["--tls=false"]

  before_script:
    - apk add --no-cache python3 py3-pip aws-cli

    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"

    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"

    - aws configure set region "$AWS_DEFAULT_REGION"

    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    - docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    
deploy:
  stage: deploy

  image: ubuntu:latest

  before_script:

    - apt update

    - apt install openssh-client -y

    - mkdir -p ~/.ssh

    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

    - chmod 600 ~/.ssh/id_rsa

    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  script:

    - |
      ssh $EC2_USER@$EC2_HOST "

      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

      docker pull $ECR_REGISTRY/$IMAGE_NAME:latest

      docker stop flask-app || true

      docker rm flask-app || true

      docker run -d \
      --name flask-app \
      -p 80:5000 \
      $ECR_REGISTRY/$IMAGE_NAME:latest
      "