stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "flask-app"
  IMAGE_TAG: "latest"
  ECR_REGISTRY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build

  image: amazon/aws-cli:latest

  services:
    - name: docker:24-dind
      command: ["--tls=false"]

  before_script:
    - yum install -y docker

    - docker version

    - aws --version

    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    - docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy

  image: ubuntu:22.04

  before_script:
    - apt-get update
    - apt-get install -y openssh-client

    - mkdir -p ~/.ssh

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa

    - chmod 600 ~/.ssh/id_rsa

    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  script:
    - |
      ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF

      aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      docker pull $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      docker stop flask-app || true

      docker rm flask-app || true

      docker run -d \
      --name flask-app \
      --restart unless-stopped \
      -p 80:5000 \
      $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      EOF