stages:
  - build
  - deploy

variables:
  IMAGE_NAME: flask-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  ECR_REGISTRY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build

  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]

  services:
    - docker:24-dind

  before_script:
    - yum install -y docker

  script:
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"

    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f app/Dockerfile app/

    - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    - docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: ubuntu:22.04

  before_script:
    - apt-get update
    - apt-get install -y openssh-client

    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  script:
  - |
    ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "

    aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
    docker login --username AWS --password-stdin $ECR_REGISTRY

    docker pull $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    docker stop flask-app || true
    docker rm flask-app || true

    docker run -d \
      --name flask-app \
      --restart unless-stopped \
      -p 80:5000 \
      $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    if [ -d /home/ubuntu/flask-monitoring-app ]; then
      cd /home/ubuntu/flask-monitoring-app
      git pull || true

      cd monitoring
      docker-compose up -d
    else
      echo 'Monitoring repo not present; skipping'
    fi
    "